#!/bin/zsh

alias honeyforwardgateway="kubectl --context=gke_honey-production_us-central1_internal-api-a port-forward deployments/internal-api-gateway 30000:8080"
alias honeyforwardstaginggateway="kubectl --context=gke_honey-staging_us-central1_internal-api-a port-forward deployments/internal-api-gateway 30000:8080"
alias honeygitpn="git syb staging && git pn && hub browse"
alias honeyshardid="node -e 'console.log(require(\"crypto\").createHash(\"md5\").update(process.argv[1]).digest(\"hex\"))'"

alias ncu="npx npm-check-updates"
alias updatedotfiles="yadm fetch && yadm reset --hard origin/master && yadm bootstrap"
