# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTFILE="$XDG_CACHE_HOME/zsh_history"
HISTSIZE=10000
SAVEHIST=100000

bindkey -e

fpath=($XDG_CONFIG_HOME/zsh/functions $fpath)

autoload -Uz compinit "$XDG_CONFIG_HOME/zsh/functions/*"
compinit

setopt noautomenu

if command -v gcloud &> /dev/null; then
  GCLOUD_SDK_DIR=`dirname $(command -v gcloud)`

  source "$GCLOUD_SDK_DIR/completion.zsh.inc"
  source "$GCLOUD_SDK_DIR/path.zsh.inc"
fi

if command -v kubectl &> /dev/null; then
  source <(kubectl completion zsh)
fi

source "$XDG_CONFIG_HOME/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme"

source "$XDG_CONFIG_HOME/zsh/aliases"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source "$XDG_CONFIG_HOME/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
