#!/bin/zsh

function updateall() {
  if command -v apt-get &> /dev/null; then
    sudo apt update
    sudo apt full-upgrade
    sudo apt autoremove
  fi

  if command -v brew &> /dev/null; then
    brew update
    brew upgrade
    brew cleanup -s
    brew cask upgrade
    brew doctor
    brew missing
  fi

  if command -v gcloud &> /dev/null; then
    gcloud components update --quiet
  fi
}
